name: Java CI with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout the Goods
        uses: actions/checkout@v4

      - name: Fire Up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle  

      - name: Get Gradle Cookin’
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.0'

      - name: Sniff Around - What’s Here?
        run: ls -R  # Check what's in the joint

      - name: Find That Sneaky `gradlew`
        run: find . -name "gradlew" -print  # Make sure the bugger exists

      - name: Give `gradlew` Some Gumption
        run: chmod +x $(find . -name "gradlew")  # Make sure it's got the legs to run

      - name: Time to Build This Beast
        run: ./gradlew build --no-daemon --scan  # Get ‘er done

      - name: Make Sure It Ain’t Broke
        run: ./gradlew test jacocoTestReport --no-daemon --scan  # Run tests and generate coverage report

      - name: Check Code Formatting with Spotless
        run: ./gradlew spotlessCheck --no-daemon  # Ensure code formatting is correct

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write  

    steps:
      - name: Grab the Repo
        uses: actions/checkout@v4

      - name: Fire Up Java Again
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle  

      - name: Hand Over the Dependency Map
        uses: gradle/actions/dependency-submission@v3